"""Add invite_code to leagues table

Revision ID: 7c74978dadc3
Revises: 
Create Date: 2025-05-23 16:23:14.701879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c74978dadc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('invite_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    op.drop_index('ix_matches_league_id', table_name='matches')
    op.drop_index('ix_matches_player1', table_name='matches')
    op.drop_index('ix_matches_player2', table_name='matches')
    op.drop_index('ix_matches_winner', table_name='matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_matches_winner', 'matches', ['winner'], unique=False)
    op.create_index('ix_matches_player2', 'matches', ['player2'], unique=False)
    op.create_index('ix_matches_player1', 'matches', ['player1'], unique=False)
    op.create_index('ix_matches_league_id', 'matches', ['league_id'], unique=False)
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_column('leagues', 'invite_code')
    # ### end Alembic commands ###
